### ISSUE TITLE
How to detect KafkaProducerSink failures?

### ISSUE THREAD

**Issue by yeryomenkom** [monix/monix-kafka#128]
Hi!
I use the same approach for producing kafka records that is described in the documentation:
```
val producer = KafkaProducerSink[String,String](producerCfg, scheduler)

// Lets pretend we have this observable of records
val observable: Observable[ProducerRecord[???,???]] = ???

observable
  // on overflow, start dropping incoming events
  .whileBusyDrop
  // buffers into batches if the consumer is busy, up to a max size
  .bufferIntrospective(1024)
  // consume everything by pushing into Apache Kafka
  .consumeWith(producer)
  // ready, set, go!
  .runToFuture
```

But, in case if serialization error occurs, the `Future` object that I get from the `runToFuture` method completes without any failure. Such behavior looks strange to me. 
I am not a very experienced user of monix. So, maybe I am doing something wrong. 

Thank you for your help!)

**Comment by Avasil** [comment]
Hello @yeryomenkom - what kind of failure do you have?
Is it `null` from custom Kafka Serializer or an exception?

**Comment by yeryomenkom** [comment]
> Hello @yeryomenkom - what kind of failure do you have?
> Is it `null` from custom Kafka Serializer or an exception?

It is exception in serializer. 
Here is my `Serde`:
```
        val failedSerde: Serde[TestObject] = Serdes.fromFn(
          serializer = (_, _) => throw new RuntimeException("serializer test exception"),
          deserializer = (_, _) => throw new RuntimeException("deserializer test exception")
        )
```

**Comment by Avasil** [comment]
`KafkaProducerSink` logs and then ignores errors when the message is sent. 
I don't know what was the motivation but I think we could add an option to provide a custom exception handler which could allow failing the producer. 

In the meantime, you could pass it already serialized messages or use `KafkaProducer` directly. Alternatively, copy existing implementation but use this in `onNext`:

```scala
val recovered = sendTask.map(_ => Continue).onErrorHandle { ex =>
  onError(ex)
  Stop
}
```

Would that work for you?

**Comment by yeryomenkom** [comment]
> Would that work for you?

Not really... I don't wanna copy paste library's code into my project... I would rather change the current behavior of the library. 

@maxstreese

**Comment by Avasil** [comment]
I mean the library will allow to customize it in the next release but I'm listing a couple of possible workarounds until it happens

**Comment by yeryomenkom** [comment]
I see. I think it is not a problem for us to wait for the next release. Thank you for your help.

**Comment by Avasil** [comment]
Hi @fdilg would you mind opening a PR with a progress that you made with this task on ScalaSpree if you still have it? It's okay if it's unfinished and you don't have time/energy to complete it, I can finalize it
I'd love to release soon with this change

**Comment by fdilg** [comment]
I created PR #150 , but I couldn't figure out why the tests for it are failing.

**Comment by Avasil** [comment]
Thank you @fdilg :)
