### ISSUE TITLE
Add option to disable commit behaviour

### ISSUE THREAD

**Issue by Avasil** [monix/monix-kafka#13]
It seems like it is not possible to disable commits from KafkaConsumerObservable because ```ObservableCommitOrder``` is always either ```isBefore``` or ```isAfter```

You can see that in [ObservableCommitOrder](https://github.com/monix/monix-kafka/blob/v0.14/kafka-0.10.x/src/main/scala/monix/kafka/config/ObservableCommitOrder.scala#L36) and [KafkaConsumerObservable](https://github.com/monix/monix-kafka/blob/v0.14/kafka-0.10.x/src/main/scala/monix/kafka/KafkaConsumerObservable.scala#L60)

I think the simplest solution is to introduce new kind of ``` ObservableCommitOrder.noAck ``` which sets other values to ``` false ```

I could issue PR later today

**Comment by alexandru** [comment]
👍

**Comment by Avasil** [comment]
#14 is merged so I close this issue
