### ISSUE TITLE
kafka 1.0

### ISSUE THREAD

**Issue by Avasil** [monix/monix-kafka#16]
Kafka 1.0 has been released and it would be cool to support it. I could give it a try but I'm not sure how to include it, another subproject?

**Comment by alexandru** [comment]
@Avasil thanks, you can give it a try.

Unfortunately it has to be another sub-project — hopefully with 1.0 they'll try keeping compatibility and we can get rid of the others in time.

**Comment by alexandru** [comment]
Sorry for the delay @Avasil, a new version will be released soon.
