### ISSUE TITLE
Add max.poll.interval to KafkaConsumerConfig

### ISSUE THREAD

**Issue by leandrob13** [monix/monix-kafka#22]
We ran into a scenario using monix kafka where we needed to use the [Allow consumer to send heartbeats from a background thread](https://cwiki.apache.org/confluence/display/KAFKA/KIP-62%3A+Allow+consumer+to+send+heartbeats+from+a+background+thread) functionality but we were not able to tune the `max.poll.interval` to achieve our goal.

I can create a PR to address this asap.

**Comment by alexandru** [comment]
👍
