### ISSUE TITLE
monix-kafka-11 not released

### ISSUE THREAD

**Issue by arlequin-nyc** [monix/monix-kafka#25]
First off thank you monix-kafka. We have been successfully using monix-kafka-9 for almost a year now, pulling 4M+ measurements/sec off of a Kafka cluster with no hiccups.

We are upgrading our internal clusters to Kafka 0.11 in the next few weeks and I noticed monix-kafka-11 was never released to mvnrepository:
https://mvnrepository.com/artifact/io.monix

Would this be possible? Was there a specific reason for not doing so? Can we help in any way?

Many thanks for the excellent work!

**Comment by Avasil** [comment]
I'll take a look as soon as I receive permission to push a new release and release current version (with 0.11) and then support for 1.0 soon after.

**Comment by arlequin-nyc** [comment]
Excellent @Avasil thank you so much!

**Comment by alexandru** [comment]
Sorry @arlequin-nyc for the delay, I've been strangled by available time, between work, monix (core) and family.

@Avasil you should now be approved to push to Sonatype. Also merge this PR first and see the RELEASES document: https://github.com/monix/monix-kafka/pull/26

**Comment by arlequin-nyc** [comment]
@alexandru thank you for your prompt reply. 
Happy to hear you manage to squeeze in some family time aside work/Monix. Looking forward to v3.0.

**Comment by Avasil** [comment]
@arlequin-nyc 
We have just released new version! :)

Try `libraryDependencies += "io.monix" %% "monix-kafka-11" % "0.15"`

Let us know if you have any issues

**Comment by leandrob13** [comment]
Closing this issue guys, given that the release is done.

**Comment by arlequin-nyc** [comment]
Gentlemen (@Avasil @leandrob13 @alexandru), thank you very much!
