### ISSUE TITLE
MAINTAINER WANTED!

### ISSUE THREAD

**Issue by alexandru** [monix/monix-kafka#27]
My time is now consumed entirely by work, [monix](https://github.com/monix/monix), [cats-effect](https://github.com/typelevel/cats-effect), [funfix](https://github.com/funfix/funfix) and family and no longer have the capacity to maintain other projects.

`monix-kafka` has actual users and I could use some help in maintaining it.

@Avasil has kindly offered to help and he has been doing a good job, but between this and his other contributions, I don't want him to burn out.

So if interested in maintaining `monix-kafka`, please add a mention below.

**Comment by leandrob13** [comment]
@alexandru I volunteer.

**Comment by alexandru** [comment]
@leandrob13 thanks, you're on 😀

**Comment by alexandru** [comment]
So we now have @leandrob13 and @Avasil as new maintainers. Closing this for now.
