### ISSUE TITLE
Allow monix.kafka.Serializer and monix.kafka.Deserializer to provide instances manually

### ISSUE THREAD

**Issue by kdrakon** [monix/monix-kafka#4]
In many cases, the reflective creation of standard (de)serializers is acceptable. However, in some circumstances, it would be desirable to still implicitly use `monix.kafka.Serializer` and `monix.kafka.Deserializer`, but rather define how the underlying classes should be instantiated. A driving use-case is with the Confluent.io (de)serializers, namely [those that use the Schema Registry Client as a constructor parameter](https://github.com/confluentinc/schema-registry/tree/master/avro-serializer/src/main/java/io/confluent/kafka/serializers).

If this is also desirable by the authors, then the follow-up PR can be a possible solution.

**Comment by alexandru** [comment]
@kdrakon thanks for the PR.

I can merge that, sure, see the small change suggested. Sorry for the delay, I've been busy, but after the PR is merged, we can release a new version.

**Comment by kdrakon** [comment]
@alexandru NP, I'll make the suggested changes ASAP 👍
