### ISSUE TITLE
Use Apache Kafka Producer and Consumer Java Map Constructor instead of Properties

### ISSUE THREAD

**Issue by sherwinschiu** [monix/monix-kafka#47]
Currently, when instantiating a new `KafkaProducer` and `KafkaConsumerObservable`, I've been running into inconsistent class not found exceptions, in particular the serializer classes. This is due to the inconsistencies of the classloaders paths, where sometimes the thread's classloader finds the class and sometimes it doesn't. The `KafkaProducer` and `KafkaConsumerObservable` passes the serializer along to Apache Kafka's producer and consumer, however Apache Kafka's producer and consumer retrieves the classname of the serializers and adds it to the properties instance instead. Eventually, it will attempt to instantiate the serializers again via the thread's classloader. I created an issue to Apache Kafka [here](https://issues.apache.org/jira/browse/KAFKA-7585). So given the current state of Apache Kafka, and a need for a more consistent way to instantiate new Monix Kafka Producers and Consumer Observables, I'm proposing we simply use the Java `Map` version of the constructor instead of the `Properties`, which preserves the passed in instances, and doesn't perform the unnecessary steps of reloading the class. The proposed [solution](https://github.com/sherwinschiu/monix-kafka/tree/feature/use-java-map-constructor) simply replaces the `Properties` instances with the Java `Map` equivalence.

**Comment by Avasil** [comment]
Feel free to make Pull Request from your branch and I think we can merge it. :) Thanks!
