### ISSUE TITLE
Scalafmt config

### ISSUE THREAD

**Issue by poslegm** [monix/monix-kafka#67]
Is it possible to add scalafmt config to this repo like in the main monix [project](https://github.com/monix/monix/blob/master/.scalafmt.conf)?

There is a rule in contributing guidelines:
> Follow the structure of the code in this repository and the indentation rules used.

But it is difficult to follow it without formal description of code style. 

I can take the job of adding a config and code base formatting.

**Comment by Avasil** [comment]
There is one but IIRC it's not enabled because the configuration wasn't satisfying. Although it was a while ago and I don't mind giving it a shot here!
