### ISSUE TITLE
Version 0.14 not published for Scala 2.12

### ISSUE THREAD

**Issue by pbvie** [monix/monix-kafka#7]
In maven central the latest version for `monix-kafka-10_2.12` seems to be 0.13

https://search.maven.org/#search%7Cga%7C1%7Cmonix-kafka

**Comment by alexandru** [comment]
Argh, OK, not sure what went wrong, will fix.

**Comment by pbvie** [comment]
Thanks for the quick reply! :slightly_smiling_face:

**Comment by pbvie** [comment]
Is there some other repo that I could use in the meantime?

**Comment by alexandru** [comment]
I'm publishing it right now. 0.13 should also work with Monix 2.3.0, since I kept binary compatibility.

**Comment by alexandru** [comment]
OK, so I published the packages on Sonatype, should take about 5 minutes to synchronise to Maven Central.

Unfortunately this happened because this project uses the [sbt-doge](https://github.com/sbt/sbt-doge) plugin to specify different Scala versions, due to the Kafka 8 client not supporting Scala 2.12 😠 and well, it misfired.

**Comment by pbvie** [comment]
Great! Thanks a lot! :slightly_smiling_face: 

Btw, the reason I was asking for another repo was because `val observable =  KafkaConsumerObservable[String,String](consumerCfg, List("my-topic"), io)` didn't work for me in 0.13. But afaik the signature for `apply` looks the same for 0.14 so I guess it's just the readme that's slightly outdated(?) :wink:

**Comment by alexandru** [comment]
@pbvie sorry, yes, it no longer has the `io` parameter. To get the same effect you can do:

```scala
KafkaConsumerObservable[String,String](consumerCfg, List("my-topic")).executeOn(io)
```

**Comment by alexandru** [comment]
Monix also has `asyncBoundary` (to jump the execution back to the default EC, which is usually `global`) and the latest version (2.3.0) also has `observeOn` which is an `asyncBoundary` that allows specifying a concrete EC.

Samples:

```scala
source.executeOn(io).asyncBoundary(BackPressure(1024))

source.executeOn(io).observeOn(computation)
```

**Comment by pbvie** [comment]
Thanks for the explanation!
