### ISSUE TITLE
[Question] Manual offset commit

### ISSUE THREAD

**Issue by pbvie** [monix/monix-kafka#8]
Is it possible to have fine control about when an offset is committed?

I've been looking at `ObservableCommitOrder` and `ObservableCommitType`. In `ObservableCommitType` it says "...specifies to do a commit before/after acknowledgement is received from downstream". Is there a way to manually signal an acknowledgement?

Or can I disable offset committing completely and call `consumer.commitSync()` myself?

Thanks! :)

**Comment by alexandru** [comment]
@pbvie unfortunately the exposed observable doesn't provide control for acknowledgement.

You could disable it like you're saying do that commit yourself.
And a suggestion for an API that provides this level of control would be cool.

The difficulty here is that in order for the downstream subscriber to do the acknowledgement, it would have to receive some kind of handle that does `consumer.commit`.

**Comment by pbvie** [comment]
@alexandru Thanks! I think manually doing the commit should work fine for me. Is it enough to set `enable.auto.commit` to false to disable automatic commits completely?

The scaladoc in `ObservableCommitOrder` and `ObservableCommitType` sound to me like monix-kafka is still doing commits even if `enable.auto.commit` is disabled.

**Comment by alexandru** [comment]
It's enough to set that value to false, the code uses it, see: https://github.com/monix/monix-kafka/blob/v0.14/kafka-0.10.x/src/main/scala/monix/kafka/KafkaConsumerObservable.scala#L60

**Comment by pbvie** [comment]
Thanks! :+1:

**Comment by velvia** [comment]
@alexandru we also have a need (in FiloDB) to completely disable the sync/commit code in monix-kafka.  The problem is that if enable.auto.commit is

true   - then monix-kafka does not commit, but Kafka driver itself does
false  - then monix-kafka itself commits

We need to truly allow this setting to be respected and turned off.  monix-kafka's own commit should be separated out IMO to allow for composability.

We have a patch ready to go if you are interested.

**Comment by Avasil** [comment]
@velvia 
Does #14 cover your use case?

If not we are open to any contributions. :)

**Comment by velvia** [comment]
Thanks, yes it does. Is this in a released version?

**Comment by Avasil** [comment]
@velvia 
It should be available in version 0.15 onwards
