### ISSUE TITLE
Can I just provide a org.apache.kafka.common.serialization.Serializer instead of the library's one?

### ISSUE THREAD

**Issue by yeryomenkom** [monix/monix-kafka#90]
Hi!
I can not get the point in having ```monix.kafka.Serializer```. Can you explain me why do I need it and why do you use that reflection approach? Can I use Serializers and Deserializers from the ```org.apache.kafka.common``` to create ```KafkaConsumerObservable``` and ```KafkaProducerSink```?

**Comment by Avasil** [comment]
Hello!

>  can not get the point in having monix.kafka.Serializer. Can you explain me why do I need it and why do you use that reflection approach?

I'm not sure to be honest. Personally I usually read `String` and then deserialize with `circe` or other library so didn't really look into it. 

@alexandru do you remember anything about it? [Link for convenience](https://github.com/monix/monix-kafka/blob/master/kafka-1.0.x/src/main/scala/monix/kafka/Serializer.scala)

> Can I use Serializers and Deserializers from the org.apache.kafka.common to create KafkaConsumerObservable and KafkaProducerSink?

I think something like this should work:

```scala
def fromKafkaSerializer[A <: KafkaSerializer[A]](kafkaSerializer: KafkaSerializer[A]): Serializer[A] =
    Serializer[A](
      className = kafkaSerializer.getClass.getName,
      classType = classOf[A]
    )
```
(can be `implicit def` I guess) but yeah, it's just an indirection.

I'm thinking about dropping it but I'm worried I'm missing use cases and breaking users' code.

**Comment by yeryomenkom** [comment]
>  I'm thinking about dropping it but I'm worried I'm missing use cases and breaking users' code.

Can we at least have possibility to create ```KafkaProducerSink``` and ```KafkaConsumerObservable``` only with serializers/deserializers from ```org.apache.kafka.common```?

Because now I have to write something like that: 
```
    val serializerK = MonixKafkaSerializer[K](
      className = "why should I provide this thing ???",
      classType = classOf[Serializer[K]],
      constructor = _ => implicitly[Serializer[K]]
    )
    val serializerV = MonixKafkaSerializer[V](
      className = "why should I provide this thing ???",
      classType = classOf[Serializer[V]],
      constructor = _ => implicitly[Serializer[V]]
    )

    KafkaProducerSink[K,V](producerConfig, Scheduler(ec))(serializerK, serializerV)
```
Instead of: 
```
implicit val serializerK: Serializer[K] = ???
implicit val serializerV: Serializer[V] = ???

KafkaProducerSink[K,V](producerConfig, Scheduler(ec))
```

**Comment by Avasil** [comment]
@yeryomenkom Sure, I will include it in the next release. Thanks for bringing it to my attention

**Comment by yeryomenkom** [comment]
I wanna open this again because https://github.com/monix/monix-kafka/pull/115 does not fix the issue.

**Comment by Avasil** [comment]
@yeryomenkom I am on vacation right now, I will take a look in about a week and see what can we do. Thanks for raising it
