### ISSUE TITLE
KafkaProducer send locks threads

### ISSUE THREAD

**Issue by voidconductor** [monix/monix-kafka#93]
Monix `KafkaProducers`'s `send` is locking threads of scheduler when tasks are executed in parallel, e. g.

```scala
val topic = "example"
val sc = Scheduler.forkJoin(12, 12)
val producer = KafkaProducer[String, Array[Byte]](config, sc)

val tasks = List.fill(12)("test")
Task.wanderUnordered(tasks)(producer.send(topic, _)).runAsync(...)
```

here's output of `async-profiler` with `-e lock` flag:
```
--- 321416121577 ns (44.57%), 19443 samples
  [ 0] monix.kafka.KafkaProducer$Implementation
  [ 1] monix.kafka.KafkaProducer$Implementation.$anonfun$send$2
  [ 2] monix.kafka.KafkaProducer$Implementation$$Lambda$7060.1333366705.run
  [ 3] akka.dispatch.TaskInvocation.run
  [ 4] akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec
  [ 5] akka.dispatch.forkjoin.ForkJoinTask.doExec
  [ 6] akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask
  [ 7] akka.dispatch.forkjoin.ForkJoinPool.runWorker
  [ 8] akka.dispatch.forkjoin.ForkJoinWorkerThread.run

```

This happens because of synchronization on producer and leads to performance degradation due to thread locking and impossibility of parallel sending

Given that apache `KafkaProducer` is thead-safe and asynchoronous one can benefit from parallel sending if batch size and linger time is high enough, when `send` is called in parallel it puts messages and callbacks on producer’s  internal buffer and sends them in batches and completes callbacks on own io thread.

**Comment by Avasil** [comment]
fixed in #95
